weekdays = {'Понедельник': 'Monday',
            'Вторник': 'Tuesday',
            'Среда': 'Wednesday',
            'Четверг': 'Thursday',
            'Пятница': 'Friday',
            'Суббота': 'Saturday',
            'Воскресенье': 'Sunday',
            }
weather_effect =   {'облачно с прояснениями': 'cloudy with clearings',
                    'сильный дождь': 'heavy rain',
                    'переменная облачность': 'partly cloudy',
                    'дождь': 'rain',
                    'возможны грозы': 'thunderstorms possible',
                    'мелкий дождь': 'light rain',
                    'небольшая облачность': 'partly cloudy',
                    'сплошная облачность': 'overcast',
                    'грозы': 'thunderstorms',
                    'ясно': 'clear',
                    'град': 'hail'
                    }
months = {'января': 'January',
        'февраля': 'February',
        'марта': 'March',
        'апреля': 'April',
        'мая': 'May',
        'июня': 'June',
        'июля': 'July',
        'августа': 'August',
        'сентября': 'September',
        'октября': 'October',
        'ноября': 'November',
        'декабря': 'December'
}